config/routes.rb
Rails.application.routes.draw do
  resources :progress_themes
  resources :progress_questions
  resources :questions
  resources :themes
  resources :faqs
  resources :absences
  resources :grades
  resources :activities
  resources :lessons
  resources :disciplines
  devise_for :users
  resources :courses
  resources :schools
  resources :discanexo

  post 'disciplines/:id' => 'disciplines#deleteAnexo'
  get 'update_users' => "grades#update_users", as: :update_users, defaults: { format: 'js' }

  get 'calendario' => 'activities#indexCalendar', as: :calendar
  
  get 'disciplines/:id/matricula' => 'disciplines#matricula', as: :matricula

  get 'themes/:id/answer' => 'themes#answer', as: :answer

  root 'activities#indexRoot'

end

app/models/absence.rb
class Absence < ActiveRecord::Base
  belongs_to :user
  belongs_to :lesson
end

app/models/activity.rb
class Activity < ActiveRecord::Base
    belongs_to :Discipline
    has_many :Grade, :dependent => :destroy

     def start_time
        self.data ##Where 'start' is a attribute of type 'Date' accessible through MyModel's relationship
    end
    
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :School
end

app/models/discanexo.rb
class Discanexo < ActiveRecord::Base
	belongs_to :Discipline
	
	has_attached_file :anexo
  	do_not_validate_attachment_file_type :anexo
end

app/models/discipline.rb
class Discipline < ActiveRecord::Base
  belongs_to :Course
  has_many :Activity, :dependent => :destroy
  has_many :Discuser, :dependent => :destroy
  has_many :Users, through: :Discuser
  belongs_to :Users
  has_many :discanexo, :dependent => :destroy

  validates_presence_of :nome, :cargahoraria

  def nomecompleto
  	"#{codigo} - #{nome}"
  end

end

app/models/discuser.rb
class Discuser < ActiveRecord::Base
      belongs_to :User
      belongs_to :Discipline
end

app/models/faq.rb
class Faq < ActiveRecord::Base
end

app/models/grade.rb
class Grade < ActiveRecord::Base
  belongs_to :User
  belongs_to :Activity, :dependent => :destroy
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :Discipline
  has_attached_file :anexo
  do_not_validate_attachment_file_type :anexo
end

app/models/progress_theme.rb
class ProgressTheme < ActiveRecord::Base
  belongs_to :user
  belongs_to :theme
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :theme
end

app/models/school.rb
class School < ActiveRecord::Base

end

app/models/theme.rb
class Theme < ActiveRecord::Base
	belongs_to :discipline
	has_one :progress_theme
	has_many :question

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :Discuser
  has_many :Discipline, through: :Discuser
  has_many :Discipline
  has_many :Grades
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  before_action :set_faq, only: [:show, :edit, :update, :destroy]

  # GET /faqs
  # GET /faqs.json
  def index
    @faqs = Faq.all
  end

  # GET /faqs/1
  # GET /faqs/1.json
  def show
  end

  # GET /faqs/new
  def new
    @faq = Faq.new
  end

  # GET /faqs/1/edit
  def edit
  end

  # POST /faqs
  # POST /faqs.json
  def create
    @faq = Faq.new(faq_params)

    respond_to do |format|
      if @faq.save
        format.html { redirect_to @faq, notice: 'Faq was successfully created.' }
        format.json { render :show, status: :created, location: @faq }
      else
        format.html { render :new }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faqs/1
  # PATCH/PUT /faqs/1.json
  def update
    respond_to do |format|
      if @faq.update(faq_params)
        format.html { redirect_to @faq, notice: 'Faq was successfully updated.' }
        format.json { render :show, status: :ok, location: @faq }
      else
        format.html { render :edit }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faqs/1
  # DELETE /faqs/1.json
  def destroy
    @faq.destroy
    respond_to do |format|
      format.html { redirect_to faqs_url, notice: 'Faq was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faq
      @faq = Faq.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def faq_params
      params.require(:faq).permit(:question, :answer)
    end
end

app/helpers/absences_helper.rb
module AbsencesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/faqs/_form.html.erb
<%= form_for(@faq) do |f| %>
  <% if @faq.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@faq.errors.count, "error") %> prohibited this faq from being saved:</h2>

      <ul>
      <% @faq.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %><br>
    <%= f.text_area :question %>
  </div>
  <div class="field">
    <%= f.label :answer %><br>
    <%= f.text_area :answer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/faqs/edit.html.erb
<h1>Editing Faq</h1>

<%= render 'form' %>

<%= link_to 'Show', @faq %> |
<%= link_to 'Back', faqs_path %>

app/views/faqs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Faqs</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Answer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @faqs.each do |faq| %>
      <tr>
        <td><%= faq.question %></td>
        <td><%= faq.answer %></td>
        <td><%= link_to 'Show', faq %></td>
        <% if current_user.admin? %>
        <td><%= link_to 'Edit', edit_faq_path(faq) %></td>
        <td><%= link_to 'Destroy', faq, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user.admin? %>
  <%= link_to 'New Faq', new_faq_path %>
<% end %>

app/views/faqs/new.html.erb
<h1>New Faq</h1>

<%= render 'form' %>

<%= link_to 'Back', faqs_path %>

app/views/faqs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @faq.question %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @faq.answer %>
</p>

<%= link_to 'Edit', edit_faq_path(@faq) %> |
<%= link_to 'Back', faqs_path %>