config/routes.rb
Rails.application.routes.draw do
  resources :progress_themes
  resources :progress_questions
  resources :questions
  resources :themes
  resources :faqs
  resources :absences
  resources :grades
  resources :activities
  resources :lessons
  resources :disciplines
  devise_for :users
  resources :courses
  resources :schools
  resources :discanexo

  post 'disciplines/:id' => 'disciplines#deleteAnexo'
  get 'update_users' => "grades#update_users", as: :update_users, defaults: { format: 'js' }

  get 'calendario' => 'activities#indexCalendar', as: :calendar
  
  get 'disciplines/:id/matricula' => 'disciplines#matricula', as: :matricula

  get 'themes/:id/answer' => 'themes#answer', as: :answer

  root 'activities#indexRoot'

end

app/models/absence.rb
class Absence < ActiveRecord::Base
  belongs_to :user
  belongs_to :lesson
end

app/models/activity.rb
class Activity < ActiveRecord::Base
    belongs_to :Discipline
    has_many :Grade, :dependent => :destroy

     def start_time
        self.data ##Where 'start' is a attribute of type 'Date' accessible through MyModel's relationship
    end
    
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :School
end

app/models/discanexo.rb
class Discanexo < ActiveRecord::Base
	belongs_to :Discipline
	
	has_attached_file :anexo
  	do_not_validate_attachment_file_type :anexo
end

app/models/discipline.rb
class Discipline < ActiveRecord::Base
  belongs_to :Course
  has_many :Activity, :dependent => :destroy
  has_many :Discuser, :dependent => :destroy
  has_many :Users, through: :Discuser
  belongs_to :Users
  has_many :discanexo, :dependent => :destroy

  validates_presence_of :nome, :cargahoraria

  def nomecompleto
  	"#{codigo} - #{nome}"
  end

end

app/models/discuser.rb
class Discuser < ActiveRecord::Base
      belongs_to :User
      belongs_to :Discipline
end

app/models/faq.rb
class Faq < ActiveRecord::Base
end

app/models/grade.rb
class Grade < ActiveRecord::Base
  belongs_to :User
  belongs_to :Activity, :dependent => :destroy
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :Discipline
  has_attached_file :anexo
  do_not_validate_attachment_file_type :anexo
end

app/models/progress_theme.rb
class ProgressTheme < ActiveRecord::Base
  belongs_to :user
  belongs_to :theme
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :theme
end

app/models/school.rb
class School < ActiveRecord::Base

end

app/models/theme.rb
class Theme < ActiveRecord::Base
	belongs_to :discipline
	has_one :progress_theme
	has_many :question

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :Discuser
  has_many :Discipline, through: :Discuser
  has_many :Discipline
  has_many :Grades
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!


  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url, notice: 'School was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit(:nome, :cnpj)
    end
end

app/helpers/absences_helper.rb
module AbsencesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/schools/_form.html.erb
<%= form_for(@school) do |f| %>
  <% if @school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% @school.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :cnpj %><br>
    <%= f.text_field :cnpj %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schools/edit.html.erb
<h1>Editing School</h1>

<%= render 'form' %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<h1>Listing Schools</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cnpj</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schools.each do |school| %>
      <tr>
        <td><%= school.nome %></td>
        <td><%= school.cnpj %></td>
        <td><%= link_to 'Show', school %></td>
        <td><%= link_to 'Edit', edit_school_path(school) %></td>
        <td><%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New School', new_school_path %>

app/views/schools/new.html.erb
<h1>New School</h1>

<%= render 'form' %>

<%= link_to 'Back', schools_path %>

app/views/schools/show.html.erb
<p>
  <strong>Nome:</strong>
  <%= @school.nome %>
</p>

<p>
  <strong>Cnpj:</strong>
  <%= @school.cnpj %>
</p>

<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>