config/routes.rb
Rails.application.routes.draw do
  resources :progress_themes
  resources :progress_questions
  resources :questions
  resources :themes
  resources :faqs
  resources :absences
  resources :grades
  resources :activities
  resources :lessons
  resources :disciplines
  devise_for :users
  resources :courses
  resources :schools
  resources :discanexo

  post 'disciplines/:id' => 'disciplines#deleteAnexo'
  get 'update_users' => "grades#update_users", as: :update_users, defaults: { format: 'js' }

  get 'calendario' => 'activities#indexCalendar', as: :calendar
  
  get 'disciplines/:id/matricula' => 'disciplines#matricula', as: :matricula

  get 'themes/:id/answer' => 'themes#answer', as: :answer

  root 'activities#indexRoot'

end

app/models/absence.rb
class Absence < ActiveRecord::Base
  belongs_to :user
  belongs_to :lesson
end

app/models/activity.rb
class Activity < ActiveRecord::Base
    belongs_to :Discipline
    has_many :Grade, :dependent => :destroy

     def start_time
        self.data ##Where 'start' is a attribute of type 'Date' accessible through MyModel's relationship
    end
    
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :School
end

app/models/discanexo.rb
class Discanexo < ActiveRecord::Base
	belongs_to :Discipline
	
	has_attached_file :anexo
  	do_not_validate_attachment_file_type :anexo
end

app/models/discipline.rb
class Discipline < ActiveRecord::Base
  belongs_to :Course
  has_many :Activity, :dependent => :destroy
  has_many :Discuser, :dependent => :destroy
  has_many :Users, through: :Discuser
  belongs_to :Users
  has_many :discanexo, :dependent => :destroy

  validates_presence_of :nome, :cargahoraria

  def nomecompleto
  	"#{codigo} - #{nome}"
  end

end

app/models/discuser.rb
class Discuser < ActiveRecord::Base
      belongs_to :User
      belongs_to :Discipline
end

app/models/faq.rb
class Faq < ActiveRecord::Base
end

app/models/grade.rb
class Grade < ActiveRecord::Base
  belongs_to :User
  belongs_to :Activity, :dependent => :destroy
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :Discipline
  has_attached_file :anexo
  do_not_validate_attachment_file_type :anexo
end

app/models/progress_theme.rb
class ProgressTheme < ActiveRecord::Base
  belongs_to :user
  belongs_to :theme
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :theme
end

app/models/school.rb
class School < ActiveRecord::Base

end

app/models/theme.rb
class Theme < ActiveRecord::Base
	belongs_to :discipline
	has_one :progress_theme
	has_many :question

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :Discuser
  has_many :Discipline, through: :Discuser
  has_many :Discipline
  has_many :Grades
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/progress_themes_controller.rb
class ProgressThemesController < ApplicationController
  before_action :set_progress_theme, only: [:show, :edit, :update, :destroy]

  # GET /progress_themes
  # GET /progress_themes.json
  def index
    @progress_themes = ProgressTheme.all
  end

  # GET /progress_themes/1
  # GET /progress_themes/1.json
  def show
  end

  # GET /progress_themes/new
  def new
    @progress_theme = ProgressTheme.new
  end

  # GET /progress_themes/1/edit
  def edit
  end

  # POST /progress_themes
  # POST /progress_themes.json
  def create
    @progress_theme = ProgressTheme.new(progress_theme_params)

    respond_to do |format|
      if @progress_theme.save
        format.html { redirect_to @progress_theme, notice: 'Progress theme was successfully created.' }
        format.json { render :show, status: :created, location: @progress_theme }
      else
        format.html { render :new }
        format.json { render json: @progress_theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /progress_themes/1
  # PATCH/PUT /progress_themes/1.json
  def update
    respond_to do |format|
      if @progress_theme.update(progress_theme_params)
        format.html { redirect_to @progress_theme, notice: 'Progress theme was successfully updated.' }
        format.json { render :show, status: :ok, location: @progress_theme }
      else
        format.html { render :edit }
        format.json { render json: @progress_theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /progress_themes/1
  # DELETE /progress_themes/1.json
  def destroy
    @progress_theme.destroy
    respond_to do |format|
      format.html { redirect_to progress_themes_url, notice: 'Progress theme was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_progress_theme
      @progress_theme = ProgressTheme.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def progress_theme_params
      params.require(:progress_theme).permit(:user_id, :theme_id, :status)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/progress_themes_helper.rb
module ProgressThemesHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/progress_themes/_form.html.erb
<%= form_for(@progress_theme) do |f| %>
  <% if @progress_theme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@progress_theme.errors.count, "error") %> prohibited this progress_theme from being saved:</h2>

      <ul>
      <% @progress_theme.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :theme_id %><br>
    <%= f.text_field :theme_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.number_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/progress_themes/edit.html.erb
<h1>Editing Progress Theme</h1>

<%= render 'form' %>

<%= link_to 'Show', @progress_theme %> |
<%= link_to 'Back', progress_themes_path %>

app/views/progress_themes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Progress Themes</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Theme</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @progress_themes.each do |progress_theme| %>
      <tr>
        <td><%= progress_theme.user %></td>
        <td><%= progress_theme.theme %></td>
        <td><%= progress_theme.status %></td>
        <td><%= link_to 'Show', progress_theme %></td>
        <td><%= link_to 'Edit', edit_progress_theme_path(progress_theme) %></td>
        <td><%= link_to 'Destroy', progress_theme, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Progress theme', new_progress_theme_path %>

app/views/progress_themes/new.html.erb
<h1>New Progress Theme</h1>

<%= render 'form' %>

<%= link_to 'Back', progress_themes_path %>

app/views/progress_themes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @progress_theme.user %>
</p>

<p>
  <strong>Theme:</strong>
  <%= @progress_theme.theme %>
</p>

<p>
  <strong>Status:</strong>
  <%= @progress_theme.status %>
</p>

<%= link_to 'Edit', edit_progress_theme_path(@progress_theme) %> |
<%= link_to 'Back', progress_themes_path %>